### ISSUE TITLE
Khmer font display not correctly

### ISSUE THREAD

**Issue by siengsotheara** [MetheaX/jasper-khmer-fonts-extension#1]
Hi bro, I have following in your description and now I have a problem with font KhmerOSMoullight, when I wrote word កម្ពុជា, after generating to PDF format in spring boot with jasper version 6.12.2 it shows the only កម្ពជា. Do you have any idea? Your answers will be thankful.
<img width="490" alt="Screen Shot 2020-06-16 at 8 12 34 PM" src="https://user-images.githubusercontent.com/13843613/84778835-bd95dc80-b00d-11ea-82c2-3dcc0afe6d24.png">

**Comment by kuylim** [comment]
Hello bro,
There are two main reasons:

1. Bugs in font **KhmerOSMoullight**, its was release since 2007 and also it wasn't submit to Google Fonts
2. Problem with IText, Jasper Report still use the old version of IText (**V2.1.7**) which is not proper compatible with Khmer Unicode. There is a confirmation from IText (**V5.5.4**) proper display Khmer Unicode (https://ask.osify.com/qa/613)

Propose solutions:
1. Looking for alternative fonts - I recommend fonts available at **Google Fonts**. In your case I suggest using **Khmer Moul** or **Khmer OS Moul**
2. Customize Jasper Report to compatible with newer version of **IText** (This is a hard work)

People out there already did customize, Please take look at this repository (https://github.com/Seuksa/iTextKhmer) to get some idea.
